[variables]
clean_command = ./gradlew clean
# deprecated
build_command = ./gradlew :distribution:archives:oss-linux-tar:assemble
# new
system.build_command = ./gradlew :distribution:archives:oss-{{OSNAME}}-tar:assemble
# deprecated
artifact_path_pattern = distribution/archives/oss-linux-tar/build/distributions/*.tar.gz
# new
system.artifact_path_pattern = distribution/archives/oss-{{OSNAME}}-tar/build/distributions/*.tar.gz
# Solr distribution URLs (Apache downloads - latest versions)
release_url = https://downloads.apache.org/solr/solr/{{VERSION}}/solr-{{VERSION}}.tgz

docker_image=solr
# major version of the JDK that is required for Solr
build.jdk = 11
# list of JDK major versions supported by Solr (requires separate JRE installation)
runtime.jdk = 11,17,21
runtime.jdk.bundled = false
